### PR TITLE
adding the quality module

### PR DESCRIPTION
**Pull request by abdelaziz-mahdy**
fixing this https://github.com/rainyl/opencv_dart/issues/216

### CODE REVIEW

**Comment by rainyl** [comment]
@abdelaziz-mahdy please also bump the version to 4.10.0+5

**Comment by rainyl** [comment]
oh sorry, i forgot this is opencv.full😥

**Comment by rainyl** [comment]
thx, i will push a new tag later to release it.

**Comment by abdelaziz-mahdy** [comment]
<3

**Pull request merged**
